apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-in
  namespace: webapp
  annotations:
  # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ingress.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 80