version: '3.8'

networks:
  mynetwork:
    driver: bridge
  
volumes:
  grafana_data:
  prometheus_data:

services:
  grafana:
    image: grafana/grafana:latest
    user: root
    container_name: grafana-server
    ports:
      - 8000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus-server
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/data:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - cadvisor
    networks:
      - mynetwork
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor-server
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - mynetwork

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - mynetwork
    ports:
      - 9100:9100


