scrape_configs:
  - job_name: mycadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          - "node_exporter:9100"