apiVersion: apps/v1
kind: Deployment
metadata:
  name: <nome-do-seu-deployment>
spec:
  selector:
    matchLabels:
      app: <nome-do-seu-deployment>
  replicas: 1
  template:
    metadata:
      labels:
        app: <nome-do-seu-deployment>
    spec:
      containers:
      - name: course-container
        image: <sua-imagem>