apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  namespace: curso
spec:
  selector:
    matchLabels:
      app: course-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: course-deployment
    spec:
      containers:
      - name: funcionario-container
        image: nginx