apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment-configmap
spec:
  selector:
    matchLabels:
      app: course-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: course-deployment
    spec:
      containers:
      - name: course-container
        image: nginx
        envFrom:
        - configMapRef:
            name: course-cfg