apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-web-deployment
  namespace: whatsapp-01
spec:
  replicas: 2
  selector:
    matchLabels:
      name: whatsapp-web
  template:
    metadata:
      labels:
        name: whatsapp-web
    spec:
      restartPolicy: "Always"
      containers:
      - name: whatsapp-web
        image: docker.whatsapp.biz/web:v2.37.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.5"
            memory : 256Mi
          requests:
            cpu: "0.25"
            memory : 128Mi
        ports:
        - containerPort: 443
          protocol: TCP
          name: web
        env:
        - name: WA_DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-engine
        - name: WA_APP_MULTICONNECT
          value: '1'
        - name: WA_DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-hostname
        - name: WA_DB_PORT
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-port
        - name: WA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-username
        - name: WA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-password
        - name: WA_DB_NAME_PREFIX
          valueFrom:
            secretKeyRef:
              name: whatsapp-config
              key: wa-db-name-prefix
        - name: WA_WEB_SERVERNAME
          value: 'whatsapp-web-service'
        volumeMounts:
        - name: whatsapp-media
          mountPath: /usr/local/wamedia-01
      volumes:
      - name: whatsapp-media
        persistentVolumeClaim:
          claimName: media-volume-claim-01